sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pipenv
  - pipenv install --dev --skip-lock

script:
  - pipenv run python -m pytest --cov-report term-missing --cov=pytac
  - pipenv run flake8
  # Run black if it has been installed (Python 3.6 and up).
  - if pipenv run which black > /dev/null 2>&1 ; then pipenv run black --check pytac test; fi

after_success:
  - coveralls
