apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pytac
  title: pytac
  description: Python Toolkit for Accelerator Controls (Pytac) is a Python library for working with elements of particle accelerators, developed at Diamond Light Source.
spec:
  type: library
  lifecycle: production
  owner: group:default/high-level-apps
